# Generated by Django 5.1.2 on 2024-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryFBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price_per_cubic_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_pallet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_6_pallets', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_15_pallets', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryFBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=255)),
                ('small_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medium_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('large_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(max_length=255)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_option_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee_per_position', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=255)),
                ('free_storage_days', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
